namespace MODELO
{
    public class Entrada
    {
        public string numFolioTrans { get; set; }
        public string pais { get; set; }
        public string indEliminacion { get; set; }
        public string indModificacion { get; set; }
        public string codSociedad { get; set; }
        public string idLoad { get; set; }
        public string ordCargue { get; set; }
        public string secuenciaViaje { get; set; }
        public string idCarrierSAP { get; set; }
        public string idExpedicionSAP { get; set; }
        public string denClaseExpedicion { get; set; }
        public string numEtapaTransp { get; set; }
        public string idOrigenSAP { get; set; }
        public string idDestinoSAP { get; set; }
        public string idClaseSAP { get; set; }
        public string idRutaSAP { get; set; }
		public string fechaCarga { get; set; }
        public string horaCitaCarga { get; set; }
        public string fechaDescarga { get; set; }
        public string horaCitaDescarga { get; set; }
        public string signatura { get; set; }
        public string idViajePeru { get; set; }
        public string suplemento1Canc { get; set; }
        public string denSuplemento1Canc { get; set; }
        public string suplemento2 { get; set; }
        public string denSuplemento2 { get; set; }
        public string suplemento3 { get; set; }
        public string denSuplemento3 { get; set; }
        public string suplemento4 { get; set; }
        public string denSuplemento4 { get; set; }
        public string estatusGlobal { get; set; }
        public string denEstatusGlobal { get; set; }
        public string denRutas { get; set; }
        public string nombTransportista { get; set; }
        public string placaVehiculo { get; set; }
        public string conductorVehiculo { get; set; }
        public string codigoConductor1 { get; set; }
        public string codigoConductor2 { get; set; }
        public string identifConductor { get; set; }
        public string tractor { get; set; }
        public string remolque1 { get; set; }
        public string remolque2 { get; set; }
        public string idTracking { get; set; }
        public string entregaSaliente { get; set; }
        public string origPedidoSAP { get; set; }
        public string shipment { get; set; }
        public string numNecesidad { get; set; }
        public string destPedidoSAP { get; set; }
        public string stEntregaSal { get; set; }
        public string stEntregaEnt { get; set; }
        public string stGralEntregaCarga { get; set; }
        public string stGralEntregaDescarga { get; set; }
        public string movSMSalida { get; set; }
        public string movSMEntrada { get; set; }
        public string indTipoTransporte { get; set; }
        public string numFolioTranspLig { get; set; }
        public string posicionEntrega { get; set; }
        public string numSKU { get; set; }
        public string descripcionProducto { get; set; }
        public string ctroLogisticoEntrega { get; set; }
        public string almacenEntrega { get; set; }
        public string palletsPlanificados { get; set; }
        public string cantSKU { get; set; }
        public string uniMedidaSKU { get; set; }
        public string pedido { get; set; }
        public string pesoBruto { get; set; }
        public string uniMedidaPesoBruto { get; set; }
        public string pesoNeto { get; set; }
        public string uniMedidaPesoNeto { get; set; }
        public string volumen { get; set; }
        public string uniMedidaVolumen { get; set; }
        public string cantBultos { get; set; }
        public string fechaSalida { get; set; }
        public string indSE { get; set; }
        public string fechaContPlantSal { get; set; }
        public string horaContPlantSal { get; set; }
        public string fechaContAgciaEnt { get; set; }
        public string horaContAgciaEnt { get; set; }
        public string fechaUltimaModif { get; set; }
        public string horaUltimaModif { get; set; }
        public string fechaSalidaPlanta { get; set; }
        public string horaSalidaPlanta { get; set; }
        public string distanciaRuta { get; set; }
        public string uniMedidaDistRuta { get; set; }
        public string costoTransporte { get; set; }
        public string monedaCostoTransp { get; set; }
        public string fechaContSal { get; set; }
        public string fechaContEnt { get; set; }
        public string numTotalEntregas { get; set; }
        public string fechaGuiaRemision { get; set; }
        public string guiaRemision { get; set; }

    }
}
